# -*- coding: utf-8 -*-
"""
Темы оформления (светлая и темная) — modern flat design
"""

THEMES = {
    "light": {
        "bg": "#f0f2f5",
        "fg": "#1a1a2e",
        "panel_bg": "#ffffff",
        "header_bg": "#ffffff",
        "section_bg": "#f7f8fa",
        "entry_bg": "#f0f2f5",
        "entry_fg": "#1a1a2e",
        "list_bg": "#ffffff",
        "list_fg": "#1a1a2e",
        "text_bg": "#ffffff",
        "text_fg": "#1a1a2e",
        "btn_bg": "#e8edf3",
        "btn_fg": "#2d3748",
        "btn_hover": "#d0d8e4",
        "status_bg": "#f0f2f5",
        "status_fg": "#718096",
        "accent": "#4f6df5",
        "accent_hover": "#3b5bdb",
        "accent_fg": "#ffffff",
        "border": "#e2e8f0",
        "separator": "#e2e8f0",
        "success": "#38a169",
        "danger": "#e53e3e",
        "danger_hover": "#c53030",
        "warning": "#ed8936",
        "muted": "#a0aec0",
    },
    "dark": {
        "bg": "#0b1020",
        "fg": "#eaf1ff",
        "panel_bg": "#11182b",
        "header_bg": "#15213a",
        "section_bg": "#11182b",
        "entry_bg": "#1a2540",
        "entry_fg": "#eaf1ff",
        "list_bg": "#131c32",
        "list_fg": "#eaf1ff",
        "text_bg": "#0f172c",
        "text_fg": "#eaf1ff",
        "btn_bg": "#1d2946",
        "btn_fg": "#d9e5ff",
        "btn_hover": "#27385e",
        "status_bg": "#0e162a",
        "status_fg": "#8fa4cc",
        "accent": "#3a7bff",
        "accent_hover": "#2e68de",
        "accent_fg": "#ffffff",
        "border": "#2a3a60",
        "separator": "#223152",
        "success": "#2fbf8f",
        "danger": "#ff6b7a",
        "danger_hover": "#e45263",
        "warning": "#ffb454",
        "muted": "#8ea2c9",
    }
}
