# -*- coding: utf-8 -*-
"""
Темы оформления (светлая и темная) — modern flat design
"""

THEMES = {
    "light": {
        "bg": "#f0f2f5",
        "fg": "#1a1a2e",
        "panel_bg": "#ffffff",
        "header_bg": "#ffffff",
        "section_bg": "#f7f8fa",
        "surface": "#ffffff",
        "surface_alt": "#f8fbff",
        "entry_bg": "#f0f2f5",
        "entry_fg": "#1a1a2e",
        "list_bg": "#ffffff",
        "list_fg": "#1a1a2e",
        "text_bg": "#ffffff",
        "text_fg": "#1a1a2e",
        "btn_bg": "#e8edf3",
        "btn_fg": "#2d3748",
        "btn_hover": "#d0d8e4",
        "status_bg": "#f0f2f5",
        "status_fg": "#718096",
        "accent": "#4f6df5",
        "accent_hover": "#3b5bdb",
        "accent_fg": "#ffffff",
        "soft_accent": "#dbe7ff",
        "border": "#e2e8f0",
        "separator": "#e2e8f0",
        "tree_header_bg": "#f8fbff",
        "tree_header_hover": "#eef4ff",
        "success": "#38a169",
        "danger": "#e53e3e",
        "danger_hover": "#c53030",
        "warning": "#ed8936",
        "warning_hover": "#dd7725",
        "muted": "#a0aec0",
    },
    "dark": {
        "bg": "#060b16",
        "fg": "#eef4ff",
        "panel_bg": "#0d1729",
        "header_bg": "#13223a",
        "section_bg": "#101b2f",
        "surface": "#111d32",
        "surface_alt": "#172640",
        "entry_bg": "#16243b",
        "entry_fg": "#eef4ff",
        "list_bg": "#0f1a2e",
        "list_fg": "#edf3ff",
        "text_bg": "#0b1424",
        "text_fg": "#eff5ff",
        "btn_bg": "#182742",
        "btn_fg": "#dbe7ff",
        "btn_hover": "#233758",
        "status_bg": "#0a1221",
        "status_fg": "#93a7c8",
        "accent": "#69a8ff",
        "accent_hover": "#8dbdff",
        "accent_fg": "#08111f",
        "soft_accent": "#22395f",
        "border": "#243654",
        "separator": "#1a2944",
        "tree_header_bg": "#16243c",
        "tree_header_hover": "#203453",
        "success": "#38d39f",
        "danger": "#ff7a88",
        "danger_hover": "#ff96a2",
        "warning": "#ffbf66",
        "warning_hover": "#ffcf88",
        "muted": "#8ea5cb",
    }
}
